"""empty message

Revision ID: 73cc55138700
Revises: 
Create Date: 2017-04-05 02:07:28.064004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import app



# revision identifiers, used by Alembic.
revision = '73cc55138700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('SET foreign_key_checks = 0;')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('properties', app.utils.sqlalchemy_json.alchemy.NestedJsonObject(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.Unicode(length=64), nullable=True),
    sa.Column('last_name', sa.Unicode(length=64), nullable=True),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('password', sa.UnicodeText(), nullable=True),
    sa.Column('temp_password', sa.UnicodeText(), nullable=True),
    sa.Column('password_expires', sa.DateTime(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_request_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_index('search', 'user', ['first_name', 'last_name'], unique=False, mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###

    op.execute('SET foreign_key_checks = 1;')


def downgrade():
    op.execute('SET foreign_key_checks = 0;')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('search', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###

    op.execute('SET foreign_key_checks = 1;')